config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  
  resources :blogs do
    collection do
        post :confirm
    end
  end

  resources :users do
    collection do
        post :confirm
    end
      member do
          get 'favorite'
      end
  end

    resources :sessions, only: [:new, :create, :show, :destroy]
    resources :favorites, only: [:create, :destroy] 
    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, length: { in: 1..140}
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :blog
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
               format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :blogs
    has_many :favorites, dependent: :destroy
    has_many :favorite_blogs, through: :favorites, source: :blog
    mount_uploader :image, ImageUploader
    validates :image, presence: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    before_action :require_logged_in!, only: [:new, :show, :edit, :update, :destroy]
    before_action :edit_blog, only: [:edit, :destroy]
  
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      BlogMailer.blog_mail(@blog).deliver
      redirect_to blogs_path, notice: "投稿しました！"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "投稿を編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"投稿を削除しました！"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def edit_blog
    unless @blog.user_id == current_user.id  
      redirect_to blogs_path, notice: "投稿者以外は編集できません！！"
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
        favorite = current_user.favorites.create(blog_id: params[:blog_id])
        redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
    end
  
    def destroy
        favorite = current_user.favorites.find_by(id: params[:id]).destroy
        redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
    end

  private
    def fevorites_params
      params.require(:fevorite).permit(:image, :image_cache)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render 'new'
      end
    end
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
    end
  end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :favorite]
  before_action :require_logged_in!, only: [:show, :edit, :update, :favorite]
  before_action :edit_user, only: [:show, :edit]
  
    
    def new
        @user = User.new
    end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
    else
        render 'new'
  end
end

  def show
    @user = User.find(params[:id])
    
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path notice: "ユーザーを編集しました！"
    else
      render 'edit'
    end
  end



  def favorite
    @user = User.find(params[:id])
    @favorites_blogs = @user.favorites
  end

end


private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :image_cache)
  end
  def set_user
    @user = User.find(params[:id])
  end
  
  def edit_user
    unless @user.id == current_user.id  
      redirect_to root_path, notice: "ユーザー本人以外は閲覧・編集できません！！"
    end 
  end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
        confirm_blogs_path
      elsif action_name == 'edit'
        blog_path
      end
    end
  end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        current_user.present?
    end

    def require_logged_in!
        redirect_to new_session_path unless logged_in?
    end
end

app/helpers/tops_helper.rb
module TopsHelper
    def index
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def choose_edit_or_new
        if action_name == 'new' 
          user_path
        elsif action_name == 'edit'
          user_path
        end
      end  
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
        <ul>
  
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class= "margin">
      <%= form.submit  %>
    </div>
  <% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %> 
  <p>画像</p>
  <%= image_tag(@blog.image.url) %>
  <%= form.hidden_field :image_cache %>
  
  <div class= "margin">
    <p>本文:<%= @blog.content %></p>
    <%= form.hidden_field :content %>
  </div> 
  <div class= "col-md-12 col-xs-12">
    <%= form.submit  "登録する" %>
  </div>
<% end %>
<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <div class= "margin col-md-12 col-xs-12">
  <%= form.submit "もどる" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h2>投稿を編集する</h2>

<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container-fluid">
  <h1>投稿一覧</h1>
  <div class="row">
    <div class="col-md-9 col-xs-12">
        <table>
          <tr>
            <th>画像</th>
            <th>記事</th>
            <th>投稿者</th>
            <th></th>
          </tr>
          <% @blogs.each do |blog| %>
          <tr>
            <td><%= image_tag(blog.image.url) %></td>
            <td><%= blog.content %></td>
            <td><%= blog.user.name %></td>
            <td><%= link_to '確認', blog_path(blog.id) %> 
            <% if logged_in? %>
              <% if blog.user_id == current_user.id %>
                <%= link_to "編集", edit_blog_path(blog.id) %> 
                <%= link_to '削除', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
              <% end %> 
            <% end %>
          </tr>
          <% end %>
        </table><br><br>
    </div>
  </div>
  
</div>
<div class= "margin">
  <a href="/" class="btn btn-default btn-sm" role="button">トップページへ</a>
</div>

app/views/blogs/new.html.erb
<h2>投稿を作成する</h2>
 
<%= render 'form' %></p>

app/views/blogs/show.html.erb
<div class="container-fluid">
  <h1>投稿確認</h1>
  <div class="row">
    <div class="col-md-9 col-xs-12">  
        <p>画像：</p>
        <%= image_tag @blog.image.url %></p>
      <div class= "margin">
        <p>内容: <%= @blog.content %></p>
      </div>

      <div class= "margin col-md-9 col-xs-12">
        <a href="/blogs" class="btn btn-default btn-sm" role="button">投稿一覧へ</a>
      </div>
    </div>
  </div>
  <% unless @blog.user_id == current_user.id %>
    <div class= "margin col-md-9 col-xs-12">  
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bigtask2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body topmargin="0">
  <header>
    <ul>
      <li><a href="/">ホーム</a></li>
      <li><a href="/blogs/new">新規作成</a></li>
      <li><a href="/blogs">投稿一覧</a></li>
    </ul>
  </header>
  
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  
  <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id) %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Login", new_session_path %>
  <% end %>

<%= yield %>
  <footer>
    <p>DIVE INTO CODE　2018年８月期　K.Sato</p>
  </footer>
</body>
</html>

app/views/tops/index.html.erb
<h1>トップページ</h1>
    <%= image_tag "hamburger.jpg" ,class: "image" %>
</div>
<div class="margin">
    <p>本サイトはレコーディングダイエットのために摂取した食事の写真とそれに対するコメントを記録するためのWEBアプリです。</p>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true ,url: choose_edit_or_new ) do |f| %>
    
   
      <%= f.label :name %>
      <%= f.text_field :name %>
    
   
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
    
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.label :image %>
      <%= f.file_field :image %>

    <div class= "margin">
      <%= f.submit %>
    </div>
    <% end %>
  

app/views/users/edit.html.erb
<h2>ユーザーを編集する</h2>

<%= render 'form' %>

app/views/users/favorite.html.erb
<h1><%= @user.name %>がお気に入りした投稿一覧</h1>

<table>
<tr>
  <th>画像</th>
  <th>記事</th>
  <th>投稿者</th>
</tr>
  <% @user.favorite_blogs.each do |blog| %>
    <tr>
      <td><%= image_tag(blog.image.url) %></td>
      <td><%= blog.content %></td>
      <td><%= blog.user.name %></td>
    </tr>
  <% end %>
</table>

<div class= "margin">
  <a href="/" class="btn btn-default btn-sm" role="button">トップページへ</a>
</div>

app/views/users/fevorite.html.erb
<h1><%= @user.name %>がお気に入りした投稿一覧</h1>

<table>
<tr>
  <th>画像</th>
  <th>記事</th>
  <th>投稿者</th>
</tr>
  <% @user.favorite_blogs.each do |blog| %>
    <tr>
    <td><%= image_tag(@blog.image.url) %><%= form.hidden_field :image_cache %></td>
      <td><%= blog.content %></td>
      <td><%= blog.user.name %></td>
    </tr>
  <% end %>
</table>

<div class= "margin">
  <a href="/" class="btn btn-default btn-sm" role="button">トップページへ</a>
</div>

app/views/users/new.html.erb
<h1>アカウントの新規作成</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :image %>
  <%= f.file_field :image %>
<div class= "margin">
  <%= f.submit "アカウントを新規作成する" %>
</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<% if @user.image.url.present? %>
    <p><%= image_tag @user.image.url %></p>
<% end %>
<p>メールアドレス: <%= @user.email %></p>

  <%= link_to "お気に入りした投稿一覧へ", favorite_user_path(@user.id) %>
  <% if logged_in? %>
  <% if @user.id == current_user.id %>
    <%= link_to "編集", edit_user_path(@user.id) %> 
  <% end %> 
<% end %>


<div class= "margin">
  <a href="/" class="btn btn-default btn-sm" role="button">トップページへ</a>
</div>